name: Testes com Robot

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop, main ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências (Python + Robot)
        run: |
          sudo apt update
          sudo apt install -y python3-pip google-chrome-stable
          pip install robotframework selenium robotframework-seleniumlibrary webdriver-manager

      - name: Baixar e configurar chromedriver
        run: |
          wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Rodar servidor local
        run: |
          npm install -g serve
          serve . -l 3000 &
          sleep 5

      - name: Executar testes Robot
        run: |
          robot -d results tests/
